exports.states = {
  "andaman and nicobar islands": "an",
  "andhra pradesh": "ap",
  "arunachal pradesh": "ar",
  "assam": "as",
  "bihar": "br",
  "chandigarh": "ch",
  "chhattisgarh": "ct",
  "dadra and nagar haveli": "dn",
  "daman and diu": "dd",
  "delhi": "dl",
  "goa": "ga",
  "gujarat": "gj",
  "haryana": "hr",
  "himachal pradesh": "hp",
  "jammu and kashmir": "jk",
  "jharkhand": "jh",
  "karnataka": "ka",
  "kerala": "kl",
  "lakshadweep": "ld",
  "madhya pradesh": "mp",
  "maharashtra": "mh",
  "manipur": "mn",
  "meghalaya": "ml",
  "mizoram": "mz",
  "nagaland": "nl",
  "odisha": "or",
  "orissa": "or",
  "puducherry": "py",
  "punjab": "pb",
  "rajasthan": "rj",
  "sikkim": "sk",
  "tamil nadu": "tn",
  "telangana": "tg",
  "tripura": "tr",
  "uttar pradesh": "up",
  "uttarakhand": "ut",
  "uttaranchal": "ut",
  "west bengal": "wb"
};
